---
title: "STAT450, Extra Credit 1"
author: "Sean Steven Alcantara"
format: 
  html:
    self-contained: true
editor: visual
---

```{r}
library(tidyverse)
library(harrypotter)
library(tidytext)
```

# Exercise 1

## (a)

Start with "y"

```{r}
str_subset(words, "^y")
```

## (b)

End with "w"

```{r}
str_subset(words, "w$")
```

## (c)

Exactly three letters long

```{r}
str_subset(words, "^...$")
```

## (d)

Only contains consonants

```{r}
str_subset(words,"[aeiou]", negate = TRUE)
```

## (e)

Start and end with vowel

```{r}
str_subset(words,"^[aeiou].*[aeiou]$")
```

# Exercise 2

```{r}
data("deathly_hallows")
length(deathly_hallows)
```

```{r}
deathly_tbl <- tibble(
  chapter = 1:37,
  text = deathly_hallows
)
```

```{r}
deathly_tbl_word_freq <- deathly_tbl |>
   unnest_tokens(word, text) |>
   anti_join(stop_words) |>
   count(word, sort = TRUE)
```

```{r}
deathly_tbl_word_freq
```

```{r}
 deathly_tbl_word_freq |>
   filter(n > 150) |>
   mutate(word = reorder(word, n)) |>
   ggplot(aes(n, word)) +
   geom_col() +
   ggtitle("Deathly Hallows")
```
